server:
  port: 9000
  connection-timeout: 1800s

elasticsearch:
   url: #es_url
   index: #index
   type: event
   statisticsIndex: stats

elk:
  testName: rvr_node_0808_1

logging:
  level:
    com.rvr.swiss.elk: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - [%t] - %msg%n"


spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
    serialization-inclusion: non_null
